"""empty message

Revision ID: 168a8d690d78
Revises: 3b4fd61dc979
Create Date: 2022-07-03 13:22:31.438780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168a8d690d78'
down_revision = '3b4fd61dc979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'abc_families', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'abc_families', type_='foreignkey')
    # ### end Alembic commands ###
