"""new stuufs

Revision ID: 3b4fd61dc979
Revises: 68c411d1f4f2
Create Date: 2022-07-01 20:03:49.152911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4fd61dc979'
down_revision = '68c411d1f4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'joint_events', 'calendar', ['calendar_id'], ['id'])
    op.add_column('members', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('lga', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('residential_state', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('lat_lng', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'lat_lng')
    op.drop_column('members', 'residential_state')
    op.drop_column('members', 'lga')
    op.drop_column('members', 'neighborhood')
    op.drop_constraint(None, 'joint_events', type_='foreignkey')
    # ### end Alembic commands ###
