"""added new column to calender

Revision ID: 68c411d1f4f2
Revises: eebb82078eec
Create Date: 2022-06-21 23:31:45.519082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c411d1f4f2'
down_revision = 'eebb82078eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('visitations_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar', 'visitations', ['visitations_id'], ['id'])
    op.create_foreign_key(None, 'visitations', 'abc_families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitations', type_='foreignkey')
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'visitations_id')
    # ### end Alembic commands ###
